### PR TITLE
chore: formatted sensor output in test library

### PR DESCRIPTION
**Pull request by sven-ruess**
This MR depends on #200 and should be applied after it.

### CODE REVIEW

**Comment by chemelli74** [comment]
I don't get the scope of this PR, anyway it needs rebase

**Comment by sven-ruess** [comment]
Hi @chemelli74,

I have done the rebase and now it can be merged without any conflicts.

I added a formatted and clean output in test library for sensor data. This is very helpful, to check, if everything is working. In the output we can see the original reply and what is done with the data. It means, what data from the reply is available for further processing.

**Comment by chemelli74** [comment]
Please:

- fix conflict
- rebase to latest code
- rename PR to be commlint compliant

**Comment by sven-ruess** [comment]
All topics are done. Further MRs will be updated after merge. I think, this is easier and conflicts are automatically resolved.

**Pull request merged**
