### PR TITLE
Python3 features for test library

### PR DESCRIPTION
**Pull request by sven-ruess**
This MR depends on #180 and should be applied after it.

### CODE REVIEW

**Comment by chemelli74** [comment]
I don't get the scope of this PR, anyway it needs rebase

**Comment by sven-ruess** [comment]
Hi @chemelli74,

I have done the needed rebase of this MR. Now it is updated and can be merged without any conflicts.

During my testing, Vodafone did an update of my cable modem. So my phone data was not available. So I added a fix for it, that it will not crash. That is the second commit.

**Comment by chemelli74** [comment]
@sven-ruess thank you for all your work but please keep in mind that each PR should address 1 and only 1 fix/improvement.

Also I'm not a fan of changing the format of print without any benefits.
Maybe we can instead use logging.

**Comment by sven-ruess** [comment]
With those changes we have a benefit. We can use a great formatting string for all outputs.
For example:
- Two decimal places for float: f"{value:.2f}"
- Dynamically right formatted strings: f"{name:>20} {value}"
- Dynamically left formatted strings: f"{name:<20} {value}"

For information about it: https://docs.python.org/3/tutorial/inputoutput.html

That is not related to logging. The logging is okay. Do you want to move this output to logging?
I do not think, that this makes sense. Logging should be used for developers to find the issue.
Output should be readable by users to understand, what is happening and working.

I will move the last commit to other MR to get it fixed together.

**Review by chemelli74 — APPROVED** [review]

**Pull request merged**
