### PR TITLE
feat: support Technicolor Vodafone Stations

### PR DESCRIPTION
**Pull request by guerda**
Replaces #39 and #43

* add implementation for login, logout and get devices
* make VodafoneStationCommonApi abstract and move some functions up and down 
* extract hash calculation, pull up convert_uptime
* make library_test support the different classes
* add param `raw` to `_get_page_result`, as not all can be parsed as json
* add param `use_html_content_type`, as German stations deliver nicely as json, so typing needs to be skipped
* only the `X-Requested-With` header is needed. If that is missing, the host request fails

### CODE REVIEW

**Comment by guerda** [comment]
I have to adapt this PR a little bit based on the generic new `_post_page_result` method.

**Comment by guerda** [comment]
This code now uses the generic POST and GET methods and also maintains the device type. The wifi band is not reported by the Vodafone Station (see the example output in the gist).

This PR should is now ready to be merged.

**Comment by guerda** [comment]
I reduced the set of headers now to the minimum so that we can use one definition.

**Review by chemelli74 — APPROVED** [review]
Thx a lot for the implementation!

**Pull request merged**
